# Copyright (c) 2026 Cisco Systems Inc or its affiliates.
#
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ftdc-pool
  namespace: metallb-system
spec:
  addresses:
  - {{ .Values.worker_node1.ip }}-{{ .Values.worker_node1.ip }}
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: ftdc-l2
  namespace: metallb-system
spec:
  ipAddressPools:
  - ftdc-pool
  interfaces:
  - {{ .Values.worker_node1.iface_name }}

