# Copyright (c) 2026 Cisco Systems Inc or its affiliates.
#
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Service template for FTD DaemonSet pods
# This creates a LoadBalancer service for each FTD pod to get unique MetalLB IPs

# Service for k8s-vpn node
apiVersion: v1
kind: Service
metadata:
  name: ftdc-k8s-worker1
  labels:
    app: FTDC_PRIMARY
    node: {{ .Values.worker_node1.name }}  
  annotations:
    metallb.universe.tf/loadBalancerIPs: {{ .Values.worker_node1.ip }} 
spec:
  type: LoadBalancer
  selector:
    app: FTDC_PRIMARY
  ports:
  - name: ssh
    port: 3000
    targetPort: 22
    protocol: TCP
  - name: https
    port: 8305
    targetPort: 8305
    protocol: TCP
  - name: snmp
    port: 161
    targetPort: 161
    protocol: UDP
  - name: fmc-reg
    port: 8302
    targetPort: 8302
    protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
