name: Python Package

on:
  push:
    branches:
      - "action_test"

jobs:
  Run-Tox:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: "Install virtualenv"
        run: |
          python -V
          python -m pip install --upgrade pip
          python -m pip install virtualenv
      - name: "Build the cluster_layer.zip"
        run: |
          pwd
          cd cluster/aws
          pwd
          python -V
          mkdir -p layer
          virtualenv ./layer/
          source ./layer/bin/activate
          python -m pip install --platform manylinux2010_x86_64 --only-binary=:all: --target=$(pwd)/lib/python3.9/site-packages pycryptodomex paramiko==2.7.1 requests==2.23.0 scp==0.13.2 jsonschema==3.2.0 cffi==1.15.1 zipp==3.1.0 importlib-metadata==1.6.0
          echo "Copy from ./layer directory to ./python\n"
          mkdir -p ./python/
          cp -r ./layer/lib/python3.9/site-packages/* ./python/
          zip -r cluster_layer.zip ./python
          deactivate
          cp cluster_layer.zip lambda-python-files/
          python make.py build

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            cluster/aws/target/cluster_layer.zip
            cluster/aws/target/cluster_manager.zip
            cluster/aws/target/cluster_lifecycle.zip
