name: Python Package

on:
  push:
    branches:
      - "action_test"

jobs:
  Run-Tox:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Test with tox
        run: |
        python -V
        mkdir -p layer
        virtualenv ./layer/
        source ./layer/bin/activate
        python -m pip install pycryptodome==3.17.0 paramiko==2.7.1 requests==2.23.0 scp==0.13.2 jsonschema==3.2.0 cffi==1.15.1 zipp==3.1.0 importlib-metadata==1.6.0
        echo "Copy from ./layer directory to ./python\n"
        mkdir -p ./python/
        cp -r ./layer/lib/python3.9/site-packages/* ./python/
        zip -r cluster_layer.zip ./python
        deactivate      
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            cluster_layer.zip
